### ISSUE TITLE
Not currently working

### ISSUE THREAD

**Issue by nrbrook** [Richienb/gitattributes-generator#3]
The generator doesn't currently work. Console error:

> www.richie-bendall.ml/:1 Access to XMLHttpRequest at 'https://api.github.com/rate_limit' from origin 'https://www.richie-bendall.ml' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by nrbrook** [comment]
https://github.community/t5/GitHub-API-Development-and/rate-limit-response-does-not-include-access-control-allow-origin/m-p/58325#M4910

<blockquote><img src="https://user-images.githubusercontent.com/18125109/32192502-576e12ae-bd82-11e7-9d94-9e6bfb03cd4d.png" width="48" align="right"><div><strong><a href="https://github.community/t5/GitHub-API-Development-and/rate-limit-response-does-not-include-access-control-allow-origin/m-p/58325#M4910">rate_limit response does not include access-control-allow-origin header?</a></strong></div><div>Requests to the rate_limit endpoint do not seem to include the "access-control-allow-origin" header any more, meaning requests are failing.</div></blockquote>

**Comment by Richienb** [comment]
It must have been a temporary issue. It might be this one: https://www.githubstatus.com/incidents/3q541nk49qmw

<blockquote><img src="https://dka575ofm4ao0.cloudfront.net/pages-twitter_logos/original/36420/GitHub-Mark-120px-plus.png" width="48" align="right"><div><strong><a href="https://www.githubstatus.com/incidents/3q541nk49qmw">Incident on 2020-05-15 20:38 UTC</a></strong></div><div>GitHub's Status Page - Incident on 2020-05-15 20:38 UTC.</div></blockquote>
